### ISSUE TITLE
Hidden tokens block movement

### ISSUE THREAD

**Issue by NdranC** [7H3LaughingMan/pf2e-elevation-ruler#2]
So I'm still on v11 and the non pathfinder version of this ruler, so it's possible all of this is not a problem in the new version (I can't update to test atm). I just wanted to bring it up since it's fairly easy to test.

When the "Tokens Block" option is enabled for hostiles, if I have a token that is hidden (this happens a lot for traps in pf2e which are actor tokens on the map) it would be treated by the ruler as a hostile and display an icon showing I'm being "slowed" by something. Which obviously is not ideal for multiple reasons.

If this is a non issue in v12 then I apologize.

**Comment by 7H3LaughingMan** [comment]
This is an issue with Elevation Ruler itself, you would need to raise this issue with them.

https://github.com/caewok/fvtt-elevation-ruler/issues

Please note, this module only adds support for the Pathfinder 2e system to Elevation Ruler.

**Comment by NdranC** [comment]
My bad. Didn't realize that's how it worked and since I don't play 5e I wasn't sure if this is a general issue or just pf2e. Thanks.
