### ISSUE TITLE
[Feature] Press Right button to create midpoints for an exact movement turns

### ISSUE THREAD

**Issue by apoapostolov** [7H3LaughingMan/pf2e-elevation-ruler#3]
Something available from Drag Ruler was that with either ENTER or right click you can create midpoints for a complex movement route where exact location is important to be shown to players.

**Comment by 7H3LaughingMan** [comment]
This module only adds support for the Pathfinder 2e system to Elevation Ruler. What you are requesting is a change to Elevation Ruler itself and as such you would need to make a request with them.

https://github.com/caewok/fvtt-elevation-ruler/issues

**Comment by apoapostolov** [comment]
Sorry about this, I mixed the two mods' support links.
